### ISSUE TITLE
Erro na ultima atualização da lib 1.2.0

### ISSUE THREAD

**Issue by leandrobudau** [eslint/eslint-visitor-keys#11]
Na ultima atualização da lib 1.1.0 para 1.2.0 ocorre um erro ao tentar instalar:

npm i eslint-visitor-keys@1.2.0 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-visitor-keys@1.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lbmoraes/.npm/_logs/2020-06-04T15_46_46_604Z-debug.log`
`

**Comment by mysticatea** [comment]
Thank you for your report.

But this is not a problem of this repo because `eslint-visitor-keys@1.2.0` is there: https://www.npmjs.com/package/eslint-visitor-keys.
Please ask npm's forum.
