### ISSUE TITLE
Upgrading ESLint fails because of Node engine dependency

### ISSUE THREAD

**Issue by danielrentz** [eslint/eslint-visitor-keys#27]
Upgrading ESLint from 7.29 to 7.30 in our project suddenly fails:
```
> yarn upgrade --latest eslint
error eslint-visitor-keys@3.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.16.1"
error Found incompatible module.
```
Seems this (and only this) package in "eslint land" is requiring NodeJS 14.17 but we are working with `>=14.16`.

**Comment by danielrentz** [comment]
Ah my fault, this dependency comes from an eslint plugin, not from eslint itself. closing...

**Comment by innocenzi** [comment]
What plugin does this come from? I have that issue since a while now, using Node `15.8`.

```
error eslint-visitor-keys@3.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.8.0
```

**Comment by martinrojas** [comment]
Why would this package drop v15 of the node. It seems like such a pointless breaking change

**Comment by aladdin-add** [comment]
node v15 has been EOL in 2021-06-01, so eslint v8.0.0 will drop it.

can someone explain why and how you encounter the issue? ( the latest eslint(7.x) should support node v15.)

**Comment by nzakas** [comment]
The version of this package that dropped Node 15 support isn't currently used by ESLint. (See [package.json](https://github.com/eslint/eslint/blob/master/package.json#L58)). If you are getting this error, it is coming from a different package.

**Comment by innocenzi** [comment]
I've no clue what it is if not this package, but I'm not tied to v15 so I just upgraded anyway.

**Comment by martinrojas** [comment]
I had no clue that Node 15 had been EOL. This makes a lot of sense. Otherwise it honestly just seemed like a very arbitrary call and this package is going to get the bulk of the searches because the Nuxt int-18 dependency tree leads to here and the error. 

For those that can't update their Node version, a temporary fix is to add a resolution to the `package.json`

`"resolutions": {
    "eslint-visitor-keys": "2.1.0"
  }`

**Comment by nzakas** [comment]
@martinrojas it sounds like you should file an issue with the Nuxt int-18 module to make sure they aren’t allowing silent major version upgrades in their package.json. Major version upgrades always contain breaking changes, so this shouldn’t be surprising.
