### ISSUE TITLE
Adding to `getKeys` blocklist

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint-visitor-keys#38]
As per the points raised in #36 by @mdjermanovic , `getKeys` might be ignoring the following additional properties, with the items in parentheses being relative to ESLint but may call for a major version bump if considering other users:

1. `type` (perf)
2. `range` (from `BaseNodeWithoutComments`) (perf)
3.  `loc` (from `SourceLocation`) (perf)
4.  `comments` and `innerComments` (from `Comment`) (fix since may be mistakenly traversed)

## User-facing impact

It is possible some custom AST could be using those properties as legitimate keys, might somehow be (ab)using `getKeys` to not expect the above properties to be excluded, or might have a traversal function which doesn't ignore those properties when iterating through them.

## What is the suggested fix?

However, from the perspective of ESLint, and I think reasonable expectations at least in a major bump, these shouldn't be allowed for traversal given that some are uniformly known not to need traversal given their fixed, special meaning (the `perf`-labeled items).

For `comments` and `innerComments` the case is even stronger to exclude because these will be traversed if present, but as per our prior exclusion of `leadingComments` and `trailingComments`, the expectation seems to be *not* to traverse `Comment` nodes even if present.

Our new tool to get keys from the TypeScript AST at least does not allow these when building our own key list (by excluding any which lead to `Line` or `Block` types), but other tools do not have access to this algorithm when using `getKeys()`.

**Comment by nzakas** [comment]
Can you expand in this? What is the user-facing impact? What is the suggested fix?

**Comment by brettz9** [comment]
> Can you expand on this? What is the user-facing impact? What is the suggested fix?

I've amended the original message.

**Comment by nzakas** [comment]
Thanks! 👍

**Comment by fasttime** [comment]
What exactly is `innerComments`? I can't find any properties with that name in ESTree or in the eslint org.

**Comment by nzakas** [comment]
Closing due to age.
