### ISSUE TITLE
Bundled types fail under "node16" module

### ISSUE THREAD

**Issue by bradzacher** [eslint/eslint-visitor-keys#46]
# Repro

```bash
$ npm i eslint-visitor-keys typescript
$ echo '{"compilerOptions":{"strict":true,"module":"Node16","moduleResolution":"node16"}}' > tsconfig.json
$ echo "import * as foo from 'eslint-visitor-keys';" > test.ts
$ npx tsc -b ./tsconfig.json
```

# Expected

No errors

# Actual

```
test.ts:1:22 - error TS7016: Could not find a declaration file for module 'eslint-visitor-keys'. '/Users/bjz/temp/playground/node_modules/eslint-visitor-keys/dist/eslint-visitor-keys.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/eslint-visitor-keys` if it exists or add a new declaration (.d.ts) file containing `declare module 'eslint-visitor-keys';`

1 import * as foo from 'eslint-visitor-keys';
                       ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

# Additional Info

https://arethetypeswrong.github.io/?p=eslint-visitor-keys%403.4.0
![image](https://user-images.githubusercontent.com/7462525/234725426-86d98b5e-08ee-472d-8ddb-5e8cf96c4f41.png)

**Comment by bradzacher** [comment]
In terms of correcting this:
1) each file listed in the `exports` should have a corresponding def file
https://github.com/eslint/eslint-visitor-keys/blob/c982093329f12c02dc87569930a6042f4095026b/package.json#L8-L17

So we should be emitting two type def files:
- `./lib/index.d.ts`
- `./dist/eslint-visitor-keys.d.cts`

Given that `eslint-visitor-keys.cjs` is a bundled file - the corresponding types file should also be bundled as well.

**Comment by bradzacher** [comment]
Additionally whilst looking into this I noticed that there is a completely unnecessary cycle in the types:

1) `./lib/index.js` defines the `VistorKeys` type
2) `./lib/visitor-keys.js` imports and consumes the `VistorKeys` type
3) `./lib/index.js` imports `./lib/visitor-keys.js`

We should move the `VisitorKeys` to `./lib/visitor-keys.js` to remove the cycle

**Comment by sam3k** [comment]
Hi @bradzacher, thank you for providing the very clear repro steps. In order to get it working locally, I added the following step:

```javascriptecho "{\n\t\"name\": \"$BASENAME\",\n\t\"version\": \"1.0.0\"\n}" > package.json
```

**Comment by sam3k** [comment]
@bradzacher would you be open to submitting a pull request to fix this?

**Comment by bradzacher** [comment]
@sam3k already got one up - #47!
